import{a as q,S as M,i as n}from"./assets/vendor-lDhL-8I6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const $="49778514-c989ee5c1575b477a31bb7b72",B="https://pixabay.com/api/";async function d(o,t){const r={key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await q.get(B,{params:r})).data}const u=document.querySelector(".gallery"),g=document.querySelector(".loader"),m=document.querySelector(".load-more"),R=new M(".gallery a",{captionsData:"alt",captionDelay:250});function p(){const o=document.querySelectorAll(".gallery img"),t=o.length;let r=0;return new Promise(i=>{o.forEach(e=>{e.addEventListener("load",()=>{r+=1,r===t&&i()})})})}function f(o){const t=o.map(({webformatURL:r,largeImageURL:i,tags:e,likes:a,views:c,comments:S,downloads:P})=>`<li class="gallery-item">
            <a href="${i}">
              <img src="${r}" alt="${e}" loading="lazy"/>
            </a>
            <div class="info">
              <p> ${a}</p>
              <p> ${c}</p>
              <p> ${S}</p>
              <p> ${P}</p>
            </div>
          </li>`).join("");u.insertAdjacentHTML("beforeend",t),R.refresh()}function E(){u.innerHTML=""}function h(){g.classList.add("visible")}function y(){g.classList.remove("visible")}function L(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}const v=document.querySelector(".form"),O=v.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");let s=1,l="";const w=15;v.addEventListener("submit",async o=>{if(o.preventDefault(),l=O.value.trim(),s=1,!l){n.warning({message:"Please enter a search term.",position:"topRight"});return}E(),b(),h();const t=await d(l,s).catch(()=>(n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),null));if(y(),!t||!t.hits.length){n.info({message:`Sorry, there are no images matching "${l}". Please try again!`,position:"topRight"});return}f(t.hits),await p();const r=Math.ceil(t.totalHits/w);s<r&&L()});x.addEventListener("click",async()=>{s+=1,h(),b();const o=await d(l,s).catch(()=>(n.error({message:"Failed to load more images.",position:"topRight"}),null));if(y(),!o||!o.hits.length){n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}f(o.hits),await p();const t=Math.ceil(o.totalHits/w);s<t?L():n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});const r=document.querySelector(".gallery-item");if(r){const i=r.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}});
//# sourceMappingURL=index.js.map
