import{a as q,S as M,i as s}from"./assets/vendor-lDhL-8I6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const $="49778514-c989ee5c1575b477a31bb7b72",B="https://pixabay.com/api/";async function u(o,t){const r={key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await q.get(B,{params:r})).data}const g=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more"),R=new M(".gallery a",{captionsData:"alt",captionDelay:250});function h(){const o=document.querySelectorAll(".gallery img"),t=o.length;let r=0;return new Promise(i=>{o.forEach(e=>{e.addEventListener("load",()=>{r+=1,r===t&&i()})})})}function p(o){const t=o.map(({webformatURL:r,largeImageURL:i,tags:e,likes:a,views:c,comments:S,downloads:P})=>`<li class="gallery-item">
            <a href="${i}">
              <img src="${r}" alt="${e}" loading="lazy"/>
            </a>
            <div class="info">
              <p> ${a}</p>
              <p> ${c}</p>
              <p> ${S}</p>
              <p> ${P}</p>
            </div>
          </li>`).join("");g.insertAdjacentHTML("beforeend",t),R.refresh()}function E(){g.innerHTML=""}function y(){m.classList.add("visible")}function L(){m.classList.remove("visible")}function b(){f.classList.remove("hidden")}function d(){f.classList.add("hidden")}const v=document.querySelector(".form"),I=v.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let n=1,l="";const w=15;v.addEventListener("submit",async o=>{if(o.preventDefault(),l=I.value.trim(),n=1,!l){s.warning({message:"Please enter a search term.",position:"topRight"});return}E(),d(),y();try{const t=await u(l,n);if(!t||!t.hits.length){s.info({message:`Sorry, there are no images matching "${l}". Please try again!`,position:"topRight"});return}p(t.hits),await h();const r=Math.ceil(t.totalHits/w);n<r&&b();const i=document.querySelector(".gallery");i&&i.scrollIntoView({behavior:"smooth"})}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"}),d()}finally{L()}});O.addEventListener("click",async()=>{n+=1,y(),d();try{const o=await u(l,n);if(!o||!o.hits.length){s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}p(o.hits),await h();const t=Math.ceil(o.totalHits/w);n<t?b():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});const r=document.querySelector(".gallery-item");if(r){const i=r.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}}catch{s.error({message:"Failed to load more images.",position:"topRight"}),d()}finally{L()}});
//# sourceMappingURL=index.js.map
